#ifndef V8_SECRETS_EXAMPLE_H
#define V8_SECRETS_EXAMPLE_H

// WiFi defaults
#define WIFI_SSID_DEFAULT "YOUR_WIFI_SSID"
#define WIFI_PASS_DEFAULT "YOUR_WIFI_PASSWORD"

// AP fallback defaults
#define AP_SSID_DEFAULT "TTGO-TCALL"
#define AP_PASS_DEFAULT "YOUR_AP_PASSWORD"
#define WEB_SERVER_PORT_DEFAULT 420

// Device identity defaults
#define DEVICE_NAME_DEFAULT "TTGO T-Call v8"
#define OWNER_NAME_DEFAULT "Device Owner"
#define MY_NUMBER_DEFAULT "+92XXXXXXXXXX"

// Firebase defaults
#define FIREBASE_PROJECT_ID_DEFAULT "YOUR_FIREBASE_PROJECT_ID"
#define FIREBASE_DATABASE_URL_DEFAULT "https://YOUR_PROJECT.firebaseio.com"
#define FIREBASE_API_KEY_DEFAULT "YOUR_FIREBASE_API_KEY"

// Polling and limits
#define POLLING_INTERVAL_SECONDS_DEFAULT 5
#define DAILY_SMS_LIMIT_DEFAULT 200
#define WEEKLY_SMS_LIMIT_DEFAULT 950
#define MONTHLY_SMS_LIMIT_DEFAULT 4900

#endif
